### ISSUE TITLE
MIME can be binary

### ISSUE THREAD

**Issue by laurencelundblade** [cbor-wg/CBORbis#121]
In table 3 the tag 36 data item is listed as a text string. Discussion in 3.4.6.3 also indicates text string.

I think it really needs to be a byte string as MIME can be binary data or ASCII text. MIME is not UTF-8. It can contain UTF-8, but it itself is never UTF-8.

**Comment by cabo** [comment]
There now also is tag 257, http://peteroupc.github.io/CBOR/binarymime.html

**Comment by paulehoffman** [comment]
Gaaah, I should have seen problems with this one long ago. Indeed, MIME messages are byte strings. The fact that we now have tag type 257 makes this messier, because the definition of this tag should all along have matched what is in 257. This leaves us with some unattractive choices:

- Deprecate 36 and suggest that people instead use 257
- Make 36 match 25 and have identical semantics for two different tags

Of these, I lean towards the second, but hope there is something better
