### ISSUE TITLE
Recommending using integers in place of bigfloat/decimal fractions

### ISSUE THREAD

**Issue by cabo** [cbor-wg/CBORbis#160]
> 3.4.4.  Decimal Fractions and Bigfloats

> For constrained applications, where there
is a choice between representing a specific number as an integer and
as a decimal fraction or bigfloat (such as when the exponent is small
and non-negative), there is a quality-of-implementation expectation
that the integer representation is used directly.

Comment from Jeffrey:

> • This section also suggests that integers be used instead of integral bigdecimals and bigfloats. That only works if the specific data model says they're equivalent. Maybe we should say specific data models SHOULD make them equivalent and then SHOULD set the preferred encoding to the integer version?

Comment from Carsten

> Generally, we have been moving away from making int and float equivalent, so I agree this recommendation needs to be reshaped.  A similar question occurs with basic floating point as well, so we should come to a common view on these.

**Comment by peteroupc** [comment]
I want to point out the following:

The same integer can be represented by different decimal fractions, by different bigfloats, and by different forms under other tags that define numeric values, such as tag 30 (rational numbers) and [tags 268-270](https://peteroupc.github.io/CBOR/extended.html) (rational numbers).  Depending on the implementation, it's not always practical to determine whether any of these forms are "equivalent" to an integer, especially because these tags allow numbers of arbitrary size.  For example, the number 86 can be represented in decimal fractions as 86 * 10^0, 860 * 10^-1, or (86*10^9999999) * 10^-9999999, each with different requirements on memory and arbitrary-precision arithmetic support.

On the other hand, for the 16- to 64-bit floating-point formats, it is relatively practical to determine whether a number in those formats is equivalent to an integer.  This is not only because these formats have a limited precision, but also because these formats encode a given number in only one way.

**Comment by cabo** [comment]
Peter, I used some of your words in my proposed addition to PR #165 to handle this issue.  Thank you!
Please check if the entire issue is addressed.

**Comment by peteroupc** [comment]
My comment was addressed in your change.

**Comment by cabo** [comment]
Covered by PR #165
