### ISSUE TITLE
Should 32-bit tag space be exhausted before allowing tags greater than 32-bits?

### ISSUE THREAD

**Issue by ecorm** [cbor-wg/CBORbis#177]
The 5.5 Numbers section allows CBOR protocols "to exclude specific integer encodings that are longer than necessary for the application, such as to save the need to implement 64-bit integers". 

However, there doesn't seem to be anything formal limiting the assignment of huge tag values greater than 32-bit. A constrained CBOR protocol wanting to avoid 64-bit integers may end-up having to support 64-bit tags if there is nothing to prevent the assignment of huge tag values.

A similar problem could arise in a Javascript implementation where tag values greater than 2^53 cannot be represented in a Number.

**Comment by jimsch** [comment]
I would expect that the fight is going to be that people want to have smaller tags rather than larger tags.  I agree with Carsten that allocation of 1+8 tags is going to be exceptionally rare until we start getting somewhat close to the 1+4 tag range being filled.  At that point as a DE I would want the ability to say that things will start being pushed to a larger value even though there are perhaps a couple of thousand values left in the smaller range.  I think this is something that can be left to the wisdom of the DE.

**Comment by cabo** [comment]
Well, except that

```
New entries in the range 0 to 23 are assigned by Standards Action.
New entries in the range 24 to 255 are assigned by Specification
Required.  New entries in the range 256 to 18446744073709551615 are
assigned by First Come First Served. 
```

I.e., no designated expert (DE) pressure even for 1+2.
