### ISSUE TITLE
core canonicalization requirements seem ambiguous

### ISSUE THREAD

**Issue by laurencelundblade** [cbor-wg/CBORbis#21]
The phrase "core canonicalization requirements" and the use of 2119 MUST suggests there is a clear distinction between encoded data that is canonical and is not, yet some of the text in the section just suggests issues that a protocol might want to address. 

I propose this be tightened up by splitting the section into two sub sections, the first being "Core Canonicalization Requirements" and the second being "Canonicalization Issues to Consider".  That way a normative reference can be given to the "Core Canonicalization Requirements" section.  It would also make things more clear for a generic encoder/decoder. 

I'm still trying to build up my understanding of canonicalization (in order to design a protocol). For example, I can't quite figure out the rationale for sorting. It seems like it will make encoders a lot more complex.  Is there some background discussion somewhere?

**Comment by jyasskin** [comment]
Mmm, yes, I intended the definition of the "core canonicalization requirements" to stop just before the paragraph starting "If a protocol …", but there's no firm boundary in https://cbor-wg.github.io/CBORbis/#c14n ending "the following restrictions". Want to send a patch?

A map requires sorting just so that each map value has exactly one representation. For example, {"a": "b", "c": "d"} is the same value as {"c": "d", "a": "b"}, so a canonical representation needs to pick just one byte sequence for them. Does that make sense?
