### ISSUE TITLE
Clarify certain aspects of tag 1

### ISSUE THREAD

**Issue by peteroupc** [cbor-wg/CBORbis#35]
Clarify the calendar basis of negative dates (which express seconds before the start of 1970) under tag 1, that is, whether they are to be applied proleptically based on the current rules with respect to leap years and the like for all prior years, without regard to Gregorian or Julian transitions or the like.

Clarify behavior of infinity and NaN under tag 1.  My implementation, for example, treats infinity and NaN as invalid.

**Comment by cabo** [comment]
I'm not sure infinite values are always undesirable -- we should check that.  Apart from that, can you check that 79f1cfe did all you were suggesting?

**Comment by peteroupc** [comment]
I have no objections to those changes.  All that is left is discussing how infinity and NaN should be treated.  Perhaps it's application-specific, too, how those values are to be interpreted.

**Comment by cabo** [comment]
I am not aware of a way to say something about leap seconds that will not be misunderstood by exactly half of the readers.  That's why we really want to reference POSIX instead of coming up with our own text.

The discontinuity that is mentioned here is one between physical time and the way it is represented in POSIX time.  The word discontinuity is indeed a bit confusing with respect to UTC, because some stretches of UTC can only be ambiguously recorded in POSIX time, but all others map fine.  So maybe we should be more specific about what kind of discontinuity is meant.
